AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Cvat test stack
Parameters:
  ServiceName:
    Type: String
    Description: A name for the service
    Default: Cvat
  DbName:
    Type: String
    Default: cvat
    Description: The name of the postgres database resource
  DbUser:
    Description: The username of the database
    Type: String
    NoEcho: true
    Default: root
  DbPassword:
    Description: The password of the database
    Type: AWS::SSM::Parameter::Value<String>
    Default: /datarock/cvat/dbpassword
    NoEcho: true
  SSLCertificateArn:
    Description: SSL certificate arn
    Type: String
  CvatECRRepositoryName:
    Description: Cvat app repo name
    Type: String
    Default: datarock/cvat
  CvatUIECRRepositoryName:
    Description: Cvat UI ECR repo name
    Type: String
    Default: datarock/cvat_ui
  CvatImageTag:
    Description: Cvat ECR image tag
    Type: String
    Default: latest
  CostGroupTag:
    Description: Cost group tag
    Type: String
    Default: ECS test
  SSHKeyPairName:
    Description: SSH keypair name
    Type: AWS::EC2::KeyPair::KeyName
    Default: ecs-keypair
Resources:
  CfnEcsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/datarock-cvat-cloudformation-deploy-temp/dae980669ffb8fcdd30ad1d747fe4004.template
      Parameters:
        KeyPairName:
          Ref: SSHKeyPairName
        SSHLocation: 10.0.0.0/16
        ServiceName:
          Ref: ServiceName
        VpcCIDR: 10.0.0.0/16
        PublicOneCIDR: 10.0.0.0/24
        PublicTwoCIDR: 10.0.1.0/24
        PrivateOneCIDR: 10.0.2.0/24
        PrivateTwoCIDR: 10.0.3.0/24
        DesiredCapacity: 1
        MaxSize: 4
        InstanceType: t2.small
        EFSNameTag: CvatEFSVolume
        SSLCertificateArn:
          Ref: SSLCertificateArn
      Tags:
      - Key: CostGroup
        Value:
          Ref: CostGroupTag
  CfnEcrStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/datarock-cvat-cloudformation-deploy-temp/87bcdf690e0fe0257b6f36c7288b403c.template
      Parameters:
        VpcId:
          Fn::GetAtt:
          - CfnEcsStack
          - Outputs.VPCId
        PrivateSubnetOne:
          Fn::GetAtt:
          - CfnEcsStack
          - Outputs.PrivateSubnetOne
        PrivateSubnetTwo:
          Fn::GetAtt:
          - CfnEcsStack
          - Outputs.PrivateSubnetTwo
        PrivateRouteTableOne:
          Fn::GetAtt:
          - CfnEcsStack
          - Outputs.PrivateRouteTableOne
        PrivateRouteTableTwo:
          Fn::GetAtt:
          - CfnEcsStack
          - Outputs.PrivateRouteTableTwo
        EcsHostSecurityGroup:
          Fn::GetAtt:
          - CfnEcsStack
          - Outputs.EcsHostSecurityGroup
        CvatECRRepositoryName:
          Ref: CvatECRRepositoryName
        CvatUIECRRepositoryName:
          Ref: CvatUIECRRepositoryName
      Tags:
      - Key: CostGroup
        Value:
          Ref: CostGroupTag
  CfnRedisStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/datarock-cvat-cloudformation-deploy-temp/7e552582afc93be01bfdd564acadde91.template
      Parameters:
        VpcId:
          Fn::GetAtt:
          - CfnEcsStack
          - Outputs.VPCId
        PrivateSubnetOne:
          Fn::GetAtt:
          - CfnEcsStack
          - Outputs.PrivateSubnetOne
        PrivateSubnetTwo:
          Fn::GetAtt:
          - CfnEcsStack
          - Outputs.PrivateSubnetTwo
        ClusterName: Cvat-redis
        EcsHostSecurityGroup:
          Fn::GetAtt:
          - CfnEcsStack
          - Outputs.EcsHostSecurityGroup
        CacheNodeType: cache.t2.micro
      Tags:
      - Key: CostGroup
        Value:
          Ref: CostGroupTag
  CfnCloudWatchStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/datarock-cvat-cloudformation-deploy-temp/914b306f2cba139197122ab5856c9b1c.template
      Parameters:
        ClusterName:
          Fn::GetAtt:
          - CfnEcsStack
          - Outputs.ClusterName
        ECSAutoScalingGroup:
          Fn::GetAtt:
          - CfnEcsStack
          - Outputs.ECSAutoScalingGroup
  CfnECSLifeCycleHookStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/datarock-cvat-cloudformation-deploy-temp/55bcdba84a3a7babf778e85fadd886b5.template
      Parameters:
        ClusterName:
          Fn::GetAtt:
          - CfnEcsStack
          - Outputs.ClusterName
        ECSAutoScalingGroup:
          Fn::GetAtt:
          - CfnEcsStack
          - Outputs.ECSAutoScalingGroup
  CfnRdsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/datarock-cvat-cloudformation-deploy-temp/c1b3aee55f431b659fe4aff82dfe7a01.template
      Parameters:
        DbName:
          Ref: DbName
        DbMasterUser:
          Ref: DbUser
        DbMasterPassword:
          Ref: DbPassword
        DbInstanceClass: db.t3.micro
        VpcId:
          Fn::GetAtt:
          - CfnEcsStack
          - Outputs.VPCId
        PrivateSubnetOne:
          Fn::GetAtt:
          - CfnEcsStack
          - Outputs.PrivateSubnetOne
        PrivateSubnetTwo:
          Fn::GetAtt:
          - CfnEcsStack
          - Outputs.PrivateSubnetTwo
        EcsHostSecurityGroup:
          Fn::GetAtt:
          - CfnEcsStack
          - Outputs.EcsHostSecurityGroup
      Tags:
      - Key: CostGroup
        Value:
          Ref: CostGroupTag
  CfnBastionStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/datarock-cvat-cloudformation-deploy-temp/3b5bd888335fba9f540ca807cee876ca.template
      Parameters:
        InstanceType: t2.micro
        KeyPairName:
          Ref: SSHKeyPairName
        PublicSubnetOne:
          Fn::GetAtt:
          - CfnEcsStack
          - Outputs.PublicSubnetOne
        PublicSubnetTwo:
          Fn::GetAtt:
          - CfnEcsStack
          - Outputs.PublicSubnetTwo
        RemoteAccessCIDR: 0.0.0.0/0
        VPCID:
          Fn::GetAtt:
          - CfnEcsStack
          - Outputs.VPCId
        EcsHostSecurityGroup:
          Fn::GetAtt:
          - CfnEcsStack
          - Outputs.EcsHostSecurityGroup
      Tags:
      - Key: CostGroup
        Value:
          Ref: CostGroupTag
  CfnCvatApiStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/datarock-cvat-cloudformation-deploy-temp/001a6c59c722670087b6228fbb6b3071.template
      Parameters:
        ClusterName:
          Fn::GetAtt:
          - CfnEcsStack
          - Outputs.ClusterName
        ServiceName: Cvat-app
        PublicListener:
          Fn::GetAtt:
          - CfnEcsStack
          - Outputs.PublicAPILoadBalancerListener
        ExternalUrl:
          Fn::GetAtt:
          - CfnEcsStack
          - Outputs.ExternalDNSName
        VpcId:
          Fn::GetAtt:
          - CfnEcsStack
          - Outputs.VPCId
        DbHost:
          Fn::GetAtt:
          - CfnRdsStack
          - Outputs.DbEndpoint
        DbName:
          Ref: DbName
        DbUser:
          Ref: DbUser
        DbPassword:
          Ref: DbPassword
        RedisHost:
          Fn::GetAtt:
          - CfnRedisStack
          - Outputs.ElastiCacheAddress
        Priority: 2
        DesiredCount: 1
        MaxCount: 4
        ImageUrl:
          Fn::Join:
          - ':'
          - - Fn::GetAtt:
              - CfnEcrStack
              - Outputs.CvatECRRepository
            - Ref: CvatImageTag
        ContainerCpu: 512
        ContainerMemory: 1024
        AllowedHosts: '*'
      Tags:
      - Key: CostGroup
        Value:
          Ref: CostGroupTag
  CfnCvatUIStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/datarock-cvat-cloudformation-deploy-temp/5e61a06daa062279f7a89b556986e7b6.template
      Parameters:
        ClusterName:
          Fn::GetAtt:
          - CfnEcsStack
          - Outputs.ClusterName
        ServiceName: Cvat-ui
        PublicListener:
          Fn::GetAtt:
          - CfnEcsStack
          - Outputs.PublicLoadBalancerListener
        ExternalUrl:
          Fn::GetAtt:
          - CfnEcsStack
          - Outputs.ExternalDNSName
        VpcId:
          Fn::GetAtt:
          - CfnEcsStack
          - Outputs.VPCId
        Priority: 2
        DesiredCount: 1
        MaxCount: 4
        ImageUrl:
          Fn::Join:
          - ':'
          - - Fn::GetAtt:
              - CfnEcrStack
              - Outputs.CvatUIECRRepository
            - Ref: CvatImageTag
        ContainerCpu: 128
        ContainerMemory: 256
      Tags:
      - Key: CostGroup
        Value:
          Ref: CostGroupTag
