AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cvat: ECR Repository for ECS'

Parameters:
  CvatECRRepositoryName:
    Description: Cvat app repo name
    Type: String
    Default: datarock/cvat
  CvatUIECRRepositoryName:
    Description: Cvat UI ECR repo name
    Type: String
    Default: datarock/cvat_ui

Resources:
# add cvat ECR repos
  CvatEcrRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref CvatECRRepositoryName
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
            {
              "rulePriority": 1,
              "description": "Only keep 1 images",
              "selection": {
                "tagStatus": "any",
                "countType": "imageCountMoreThan",
                "countNumber": 1
              },
              "action": { "type": "expire" }
            }]
          }

  CvatUIEcrRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref CvatUIECRRepositoryName
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
            {
              "rulePriority": 1,
              "description": "Only keep 1 images",
              "selection": {
                "tagStatus": "any",
                "countType": "imageCountMoreThan",
                "countNumber": 1
              },
              "action": { "type": "expire" }
            }]
          }
Outputs:
  CvatECRRepository:
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${CvatEcrRepo}"
  CvatUIECRRepository:
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${CvatUIEcrRepo}"
