AWSTemplateFormatVersion: 2010-09-09
Description: Bastion host setup

Parameters:
  InstanceType:
    Type: String
    Description: The instance type to use for the EC2 instance
    Default: t3.nano
  KeyPairName:
    Type: String
    Description: The name of the SSH key pair
  RemoteAccessCIDR:
    Type: String
    Description: RemoteAccessCIDR
  VPCID:
    Type: String
    Description: VPCID
  PublicSubnetOne:
    Type: String
    Description: PrivateSubnetOne
  PublicSubnetTwo:
    Type: String
    Description: PrivateSubnetTwo
  EcsHostSecurityGroup:
    Type: String
    Description: EcsHostSecurityGroup

Resources:

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchTemplate:
        LaunchTemplateId:
          Ref: LaunchTemplate
        Version:
          Fn::GetAtt: LaunchTemplate.LatestVersionNumber
      VPCZoneIdentifier:
        - !Ref PublicSubnetOne
        - !Ref PublicSubnetTwo
      MinSize: 0
      MaxSize: 1
      DesiredCapacity: 0

  BastionSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enables SSH Access to Bastion Hosts
      VpcId: !Ref VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref RemoteAccessCIDR
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: !Ref RemoteAccessCIDR

  EcsSecurityGroupIngressFromBastion:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Ingress from Bastion to EcsInstance
      GroupId: !Ref 'EcsHostSecurityGroup'
      IpProtocol: -1
      SourceSecurityGroupId: !Ref 'BastionSecurityGroup'

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        InstanceType:
          Ref: InstanceType
        ImageId:  ami-0b8b10b5bf11f3a22
        NetworkInterfaces:
          - AssociatePublicIpAddress: true
            DeleteOnTermination: true
            DeviceIndex: 0
            Groups:
              - !Ref BastionSecurityGroup
        KeyName:
          Ref: KeyPairName
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: Bastion Host
          - ResourceType: volume
            Tags:
              - Key: Name
                Value: Bastion Host
        InstanceMarketOptions:
          MarketType: spot
          SpotOptions:
            SpotInstanceType: one-time
            InstanceInterruptionBehavior: terminate
        UserData:
          Fn::Base64:
            Fn::Join:
              - ''
              - - "#!/bin/bash\n"
                - "yum -y --security update\n"