AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cvat: ECR Repository for ECS'

Parameters:
  VpcId:
    Type: String
    Description: The Id for the Vpc used for deployment
  PrivateSubnetOne:
    Type: String
  PrivateSubnetTwo:
    Type: String
  PrivateRouteTableOne:
    Type: String
  PrivateRouteTableTwo:
    Type: String
  EcsHostSecurityGroup:
    Type: String
    Description: The SecurityGroup for containers
  CvatECRRepositoryName:
    Description: Cvat app repo name
    Type: String
    Default: datarock/cvat
  CvatUIECRRepositoryName:
    Description: Cvat UI ECR repo name
    Type: String
    Default: datarock/cvat_ui

Resources:
# add cvat ECR repos
  CvatEcrRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref CvatECRRepositoryName
  CvatUIEcrRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref CvatUIECRRepositoryName
  EcrEndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Access from the containers
      VpcId: !Ref VpcId
  EcrEndpointIngressFromECS:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Ingress from containers
      GroupId: !Ref 'EcrEndpointSecurityGroup'
      IpProtocol: -1
      SourceSecurityGroupId: !Ref 'EcsHostSecurityGroup'
  EcrEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - !Ref EcrEndpointSecurityGroup
      ServiceName: com.amazonaws.ap-southeast-2.ecr.dkr
      SubnetIds:
        - !Ref PrivateSubnetOne
        - !Ref PrivateSubnetTwo
      VpcEndpointType: Interface
      VpcId: !Ref 'VpcId'
  # arn:aws:s3:::prod-region-starport-layer-bucket/*
  S3Endpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      RouteTableIds:
        - !Ref PrivateRouteTableOne
        - !Ref PrivateRouteTableTwo
      ServiceName: com.amazonaws.ap-southeast-2.s3
      VpcId: !Ref 'VpcId'
Outputs:
  CvatECRRepository:
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${CvatEcrRepo}"
  CvatUIECRRepository:
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${CvatUIEcrRepo}"
